services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: part13-pg